### PR TITLE
API cleanups

### PR DESCRIPTION
**Pull request by Jarlakxen**
This is for closing ensime/ensime-node#22

### CODE REVIEW

**Comment by hedefalk** [comment]
Oh, sorry, travis didn't really work on the last PR either, did it? Could you look at that? Seems something with param to jasmine is messed up?

**Comment by Jarlakxen** [comment]
I'm going to take a look. It's strange, because I don't have any problems in my local enviroment and also in the logs there is this message:

```
Error: spawn sbt ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by Jarlakxen** [comment]
I changed the language of travis to cpp to scala because sbt is required for the `full-stack-smoke-test.spec.ts`

**Comment by Jarlakxen** [comment]
It looks like that Travis doesn't support Scala for osx travis-ci/travis-ci#2316

**Comment by Jarlakxen** [comment]
Well, the problem was that travis was trying to run all the tests including integration tests. I tried to make it run but the test was failing, so I removed the integration tests.

**Comment by hedefalk** [comment]
I really want travis to run the integration tests too :( But maybe it's to slow. I had problems with that before…

**Comment by hedefalk** [comment]
Look here: https://travis-ci.org/ensime/ensime-node/builds

**Comment by Jarlakxen** [comment]
Now that ITs are excluded from the tests, this PR going to fix the master broken build.

**Comment by hedefalk** [comment]
@Jarlakxen Sorry, I'm not sure I follow. What is the reason you have to disable integration tests? I really would like to have them :)

**Comment by Jarlakxen** [comment]
Oh! Sorry for not been clear! =P
Well, one the problems is that we need SBT for running the test. I can switch language to scala in the travis file, but scala is not available for osx. In this commit https://github.com/ensime/ensime-node/pull/32/commits/07a87699da2c798412c8071018906f8382cd3095 I switched to scala and removed osx but the integration test failed. ( You can check the build here https://travis-ci.org/ensime/ensime-node/builds/234659506 ). I run the test locally and It works without any problem =S.

Just as a side note, I have another branch ready to make a PR in which I rewrote the integration tests, to tests the API, because I added a new command, and also improve a lot of other things =). This is the branch https://github.com/Jarlakxen/ensime-node/tree/new-commands and this is the new integration test I coded https://github.com/Jarlakxen/ensime-node/blob/new-commands/src/spec-integration/server-api.spec.ts

**Comment by hedefalk** [comment]
Ok, cool. I added a private drone before, but can't really run it for PR's
because security. That's too bad. I want to revisit that stuff because I
really want good test coverage and integration tests on PR's. travis just
doesn't seem to cut it.

**Comment by Jarlakxen** [comment]
I hope you can make it work =)
Is there anything else you want me to do, to close this PR?

**Comment by hedefalk** [comment]
I'll merge. It's not this PR that broke integration tests anyway :)

Let's see what we can do in the future to get good test coverage. Thanks!

**Pull request merged**
