### PR TITLE
TS Linting

### PR DESCRIPTION
**Pull request by Jarlakxen**
I would like to fix the code mixups, I think it could help for future contributions. For example; indentation ( 2 spaces vs 4 spaces ), quotemark  ( double vs single ), line semicolon and spacing. I looked at  the code and I set, from what I think, is the general convention. If you like, could change the rules.
I limited my changes only to code style, so the logic is the same.
I know that due to the changes in the code formatting, this PR It could be very dificult to follow. =)

### CODE REVIEW

**Comment by hedefalk** [comment]
Thanks for the contrib! I gotta take a look at this and decide upon 2 vs 4 spaces. Do you have any pointers here? Seems the ts community isn't that decided upon anything when I google :)

**Comment by hedefalk** [comment]
Screw it, I'm merging, seems you did the homework. It's a great thing to have some standard set :)

Thanks!

**Comment by hedefalk** [comment]
@Jarlakxen Just a follow up. I noticed you used a pretty old version of tslint. Is there a reason for this?

**Comment by Jarlakxen** [comment]
Mh... I think I completely forgot to update that dependency. Probably I took that version from an example.
Sorry about that! =S

**Comment by hedefalk** [comment]
NP, I'm having a look myself so don't spend any time on it :)

**Pull request merged**
