### PR TITLE
Bump to 0.10.0

### PR DESCRIPTION
**Pull request by mads-hartmann**
There are a couple of changes on master that hasn't been released. I would like to use those changes in the atom package.

### CODE REVIEW

**Comment by mads-hartmann** [comment]
@hedefalk @Jarlakxen How do feel about creating a breaking release now? Has travis been configured to publish or are there manual steps involved in publishing the package?

**Comment by hedefalk** [comment]
Go for it, I think the current status of the released version is in such decay anyways.

**Comment by mads-hartmann** [comment]
@hedefalk How do I cut a release of this package? I'd love to have it just release on every push to master :)

**Comment by hedefalk** [comment]
`npm publish` I think… Maybe I need to give you permissions there too…

**Comment by hedefalk** [comment]
That's probably the main reason I haven't published - I forgot how to do it :)

**Comment by hedefalk** [comment]
Oh, did npm publish which went through but with errors:
https://gist.github.com/hedefalk/3e66f60714714675f8805ef68f97acba

**Comment by mads-hartmann** [comment]
@hedefalk Awesome, I'll fix those error in the weekend :) In the meantime, can you figure out how to give me publish rights? Right now I get

```[09:52:59] Finished 'build' after 5.54 μs
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by hedefalk** [comment]
ts-errors… Maybe it's an env thing…?

I'll look at the npm perm…

**Comment by hedefalk** [comment]
@mads-hartmann What's your npm user? (create one if you haven't)

**Comment by mads-hartmann** [comment]
@hedefalk Didn't have one. I'm `mads-hartmann` on npm now ;)

**Comment by hedefalk** [comment]
You should be good now:

```
~/d/p/ensime-node ❯❯❯ npm owner ls                                                                                                                                                                     master ◼
hedefalk <hedefalk@gmail.com>
~/d/p/ensime-node ❯❯❯ npm owner add mads-hartmann                                                                                                                                                      master ◼
+ mads-hartmann (ensime-client)
~/d/p/ensime-node ❯❯❯ npm owner ls                                                                                                                                                                     master ◼
mads-hartmann <mads379@gmail.com>
hedefalk <hedefalk@gmail.com>
```

**Comment by mads-hartmann** [comment]
Awesome, it works 👍  How did you manage to cut a release? The TS errors didn't stop you?

**Comment by hedefalk** [comment]
Apparently not. That frightens me …

**Comment by mads-hartmann** [comment]
@hedefalk Haha, scary :) I've created https://github.com/ensime/ensime-node/issues/36 to do it on travis :)

**Pull request merged**
